"""Timeslots and interviews models.

Revision ID: f2bfea05fe49
Revises: e7c52425b00a
Create Date: 2018-06-10 12:20:54.601532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2bfea05fe49'
down_revision = 'e7c52425b00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', postgresql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='days_of_week'), nullable=False),
    sa.Column('hour', postgresql.ENUM('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', name='hours'), nullable=False),
    sa.Column('minute', postgresql.ENUM('0', '15', '30', '45', name='minutes'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('duration_in_timeslots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start'], ['timeslots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('candidates_timeslots', sa.Column('timeslot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidates_timeslots', 'timeslots', ['timeslot_id'], ['id'])
    op.drop_column('candidates_timeslots', 'end')
    op.drop_column('candidates_timeslots', 'start')
    op.add_column('employees_timeslots', sa.Column('timeslot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees_timeslots', 'timeslots', ['timeslot_id'], ['id'])
    op.drop_column('employees_timeslots', 'end')
    op.drop_column('employees_timeslots', 'start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_timeslots', sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('employees_timeslots', sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees_timeslots', type_='foreignkey')
    op.drop_column('employees_timeslots', 'timeslot_id')
    op.add_column('candidates_timeslots', sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('candidates_timeslots', sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidates_timeslots', type_='foreignkey')
    op.drop_column('candidates_timeslots', 'timeslot_id')
    op.drop_table('interviews')
    op.drop_table('timeslots')
    # ### end Alembic commands ###
